In [2]:
import pandas as pd

df=pd.read_csv("c:/Users/parva/OneDrive/Desktop/COACHX LIVE/PYTHON/PYTHON_PRACTISE/PRACTICAL/startups.csv")

df

          RND      ADMIN        MKT       STATE     PROFIT
0   165349.20  136897.80  471784.10    New York  192261.83
1   162597.70  151377.59  443898.53  California  191792.06
2   153441.51  101145.55  407934.54     Florida  191050.39
3   144372.41  118671.85  383199.62    New York  182901.99
4   142107.34   91391.77  366168.42     Florida  166187.94
5   131876.90   99814.71  362861.36    New York  156991.12
6   134615.46  147198.87  127716.82  California  156122.51
7   130298.13  145530.06  323876.68     Florida  155752.60
8   120542.52  148718.95  311613.29    New York  152211.77
9   123334.88  108679.17  304981.62  California  149759.96
10  101913.08  110594.11  229160.95     Florida  146121.95
11  100671.96   91790.61  249744.55  California  144259.40
12   93863.75  127320.38  249839.44     Florida  141585.52
13   91992.39  135495.07  252664.93  California  134307.35
14  119943.24  156547.42  256512.92     Florida  132602.65
15  114523.61  122616.84  261776.23    New York  129917.04
16   78013.11  121597.55  264346.06  California  126992.93
17   94657.16  145077.58  282574.31    New York  125370.37
18   91749.16  114175.79  294919.57     Florida  124266.90
19   86419.70  153514.11       0.00    New York  122776.86
20   76253.86  113867.30  298664.47  California  118474.03
21   78389.47  153773.43  299737.29    New York  111313.02
22   73994.56  122782.75  303319.26     Florida  110352.25
23   67532.53  105751.03  304768.73     Florida  108733.99
24   77044.01   99281.34  140574.81    New York  108552.04
25   64664.71  139553.16  137962.62  California  107404.34
26   75328.87  144135.98  134050.07     Florida  105733.54
27   72107.60  127864.55  353183.81    New York  105008.31
28   66051.52  182645.56  118148.20     Florida  103282.38
29   65605.48  153032.06  107138.38    New York  101004.64
30   61994.48  115641.28   91131.24     Florida   99937.59
31   61136.38  152701.92   88218.23    New York   97483.56
32   63408.86  129219.61   46085.25  California   97427.84
33   55493.95  103057.49  214634.81     Florida   96778.92
34   46426.07  157693.92  210797.67  California   96712.80
35   46014.02   85047.44  205517.64    New York   96479.51
36   28663.76  127056.21  201126.82     Florida   90708.19
37   44069.95   51283.14  197029.42  California   89949.14
38   20229.59   65947.93  185265.10    New York   81229.06
39   38558.51   82982.09  174999.30  California   81005.76
40   28754.33  118546.05  172795.67  California   78239.91
41   27892.92   84710.77  164470.71     Florida   77798.83
42   23640.93   96189.63  148001.11  California   71498.49
43   15505.73  127382.30   35534.17    New York   69758.98
44   22177.74  154806.14   28334.72  California   65200.33
45    1000.23  124153.04    1903.93    New York   64926.08
46    1315.46  115816.21  297114.46     Florida   49490.75
47       0.00  135426.92       0.00  California   42559.73
48     542.05   51743.15       0.00    New York   35673.41
49       0.00  116983.80   45173.06  California   14681.40

In [3]:
df.head()

         RND      ADMIN        MKT       STATE     PROFIT
0  165349.20  136897.80  471784.10    New York  192261.83
1  162597.70  151377.59  443898.53  California  191792.06
2  153441.51  101145.55  407934.54     Florida  191050.39
3  144372.41  118671.85  383199.62    New York  182901.99
4  142107.34   91391.77  366168.42     Florida  166187.94

In [4]:
df.tail()

        RND      ADMIN        MKT       STATE    PROFIT
45  1000.23  124153.04    1903.93    New York  64926.08
46  1315.46  115816.21  297114.46     Florida  49490.75
47     0.00  135426.92       0.00  California  42559.73
48   542.05   51743.15       0.00    New York  35673.41
49     0.00  116983.80   45173.06  California  14681.40

In [5]:
df.head(7)

         RND      ADMIN        MKT       STATE     PROFIT
0  165349.20  136897.80  471784.10    New York  192261.83
1  162597.70  151377.59  443898.53  California  191792.06
2  153441.51  101145.55  407934.54     Florida  191050.39
3  144372.41  118671.85  383199.62    New York  182901.99
4  142107.34   91391.77  366168.42     Florida  166187.94
5  131876.90   99814.71  362861.36    New York  156991.12
6  134615.46  147198.87  127716.82  California  156122.51

In [6]:
df.shape

(50, 5)

In [9]:
df['PROFIT'].head(3)

0    192261.83
1    191792.06
2    191050.39
Name: PROFIT, dtype: float64

In [14]:
df.loc[2:7,['PROFIT','MKT']]

      PROFIT        MKT
2  191050.39  407934.54
3  182901.99  383199.62
4  166187.94  366168.42
5  156991.12  362861.36
6  156122.51  127716.82
7  155752.60  323876.68

In [16]:
df.iloc[3:5,3:5]

      STATE     PROFIT
3  New York  182901.99
4   Florida  166187.94

In [ ]:
df['STATE'].head(7)

In [5]:
stud={
    'id':[1,2,3,4],
    'name':['ramya','rama','deepa','charu'],
    'course':['sc','scio','math','geo'],
    'sec':['A','B','A','C'],
    'marks':[100,340,120,250]
}

In [12]:
st=pd.DataFrame(stud)

st

   id   name course sec  marks
0   1  ramya     sc   A    100
1   2   rama   scio   B    340
2   3  deepa   math   A    120
3   4  charu    geo   C    250

In [15]:
st[st['marks']>120]

   id   name course sec  marks
1   2   rama   scio   B    340
3   4  charu    geo   C    250

In [19]:
st[(st['sec']=='A') & (st['marks']>100)]

   id   name course sec  marks
2   3  deepa   math   A    120

In [6]:
cr=pd.read_csv('c:/Users/parva/OneDrive/Desktop/COACHX LIVE/PYTHON/PYTHON_PRACTISE/PRACTICAL/cars.csv')

cr

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,NaN,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,NaN,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,NaN,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

In [23]:
cr.shape

(93, 28)

In [24]:
cr.columns

Index(['id', 'Manufacturer', 'Model', 'Type', 'Min.Price', 'Price',
       'Max.Price', 'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain',
       'Cylinders', 'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile',
       'Man.trans.avail', 'Fuel.tank.capacity', 'Passengers', 'Length',
       'Wheelbase', 'Width', 'Turn.circle', 'Rear.seat.room', 'Luggage.room',
       'Weight', 'Origin', 'Make'],
      dtype='object')

In [ ]:
#sort value

cr.sort_values(by='Model',ascending=False)

In [33]:
cr[['Cylinders','AirBags']].sort_values(by='AirBags',ascending=False)

   Cylinders      AirBags
41         4  Driver only
48         6  Driver only
35         6  Driver only
36         6  Driver only
37         8  Driver only
..       ...          ...
82         3          NaN
87         4          NaN
88         5          NaN
89         4          NaN
90         6          NaN

[93 rows x 2 columns]

In [34]:
#group by

cr.columns

Index(['id', 'Manufacturer', 'Model', 'Type', 'Min.Price', 'Price',
       'Max.Price', 'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain',
       'Cylinders', 'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile',
       'Man.trans.avail', 'Fuel.tank.capacity', 'Passengers', 'Length',
       'Wheelbase', 'Width', 'Turn.circle', 'Rear.seat.room', 'Luggage.room',
       'Weight', 'Origin', 'Make'],
      dtype='object')

In [ ]:
cr.groupby(by='RPM').count()

In [ ]:
cr.groupby(by=['Origin','Wheelbase']).count()

In [46]:
cr.groupby(by='Price').RPM.sum()

Price
7.4      5000
8.0      5500
8.3      5000
8.4     11300
8.6      6000
        ...
37.7     5500
38.0     5000
40.1     6000
47.9     6000
61.9     5500
Name: RPM, Length: 81, dtype: int64

In [48]:
#missing values

import numpy as np

dff={
    'id':[1,2,np.nan],
    'name':['shat',np.nan,np.nan],
    'dep':['it',np.nan,'cs']
}

d=pd.DataFrame(dff)
d

    id  name  dep
0  1.0  shat   it
1  2.0   NaN  NaN
2  NaN   NaN   cs

In [49]:
d.isnull()

      id   name    dep
0  False  False  False
1  False   True   True
2   True   True  False

In [50]:
d.notnull()

      id   name    dep
0   True   True   True
1   True  False  False
2  False  False   True

In [52]:
d.isnull().sum()

id      1
name    2
dep     1
dtype: int64

In [53]:
#fillin value

d.fillna(0)

    id  name dep
0  1.0  shat  it
1  2.0     0   0
2  0.0     0  cs

In [3]:
#joints
import pandas as pd
ddpt={
    'deptid':[1,2,3,4,5,6],
    'depname':['cs','it','ec','me','el','ml']
}

dept=pd.DataFrame(ddpt)
dept

   deptid depname
0       1      cs
1       2      it
2       3      ec
3       4      me
4       5      el
5       6      ml

In [11]:
employ={
    'eid':[i for i in range(100,106)],
    'ename':['sa','da','ram','pra','mok','par'],
    'edesignation':['hr','anala','manger','leader','tl','lead'],
    'deptidd':[2,4,5,8,7,2]
}

ep=pd.DataFrame(employ)

ep

   eid ename edesignation  deptidd
0  100    sa           hr        2
1  101    da        anala        4
2  102   ram       manger        5
3  103   pra       leader        8
4  104   mok           tl        7
5  105   par         lead        2

In [75]:
#joints

innerjoin=pd.merge(ep,dept,how='inner' , left_on='deptidd', right_on='deptid')

innerjoin

   eid ename edesignation  deptidd  deptid depname
0  100    sa           hr        2       2      it
1  101    da        anala        4       4      me
2  102   ram       manger        5       5      el
3  105   par         lead        2       2      it

In [12]:
ep['ename'].dtype

dtype('O')